# Generated by Django 6.0.3 on 2026-03-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фінальна ціна'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Чи оплачено'),
        ),
    ]
