# Generated by Django 6.0.3 on 2026-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_project_final_price_project_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Очікує оплати'), ('frozen', 'Очікує підтвердження розробника'), ('paid', 'Оплачено')], default='unpaid', max_length=20, verbose_name='Статус оплати'),
        ),
    ]
