# Generated by Django 6.0.3 on 2026-03-19 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_client', 'Очікує відповіді замовника'), ('pending_developer', 'Вам запропонували проєкт'), ('approved', 'Контракт підписано (В розробці)'), ('rejected', 'Відхилено')], default='pending_client', max_length=20)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_hours', models.IntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_applications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='teams.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
